spring:
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.mongo.MongoAutoConfiguration
      - org.springframework.boot.autoconfigure.mongo.MongoReactiveAutoConfiguration

db:
  mongodb:
    replicaset:
      root_uri: ${MONGO_URL}
      database: ${MONGO_INITDB_DATABASE}
      replicaset_name: ${MONGO_REPLICA_SET_NAME}
      authentication-database: ${RS_AUTH}
      username: ${MONGO_INITDB_ROOT_USERNAME}
      password: ${MONGO_INITDB_ROOT_PASSWORD}