version: "3.5"

services:

  mongodb-secrets:
    container_name: mongo1-db
    image: mongo:4.4.4
    ports:
      - 27017:27017
    environment:
# ROOT-DB -----------------------------------------------------------------
# MONGO-COMPASS-URL: mongodb://root:root@localhost:27017/?authSource=admin&readPreference=primary&appname=MongoDB%20Compass&ssl=false
      MONGO_INITDB_DATABASE_FILE: /run/secrets/root_db_admin
      MONGO_INITDB_ROOT_USERNAME_FILE: /run/secrets/root_db_username
      MONGO_INITDB_ROOT_PASSWORD_FILE: /run/secrets/root_db_password
# MONGO_INITDB_ROOT_USERNAME: root_username
# MONGO_INITDB_ROOT_PASSWORD: root_password

# WEB-APP-DB --------------------------------------------------------------
      MONGO_DATABASE: /run/secrets/app_db_name
      MONGO_USERNAME_FILE: /run/secrets/app_db_username
      MONGO_PASSWORD_FILE: /run/secrets/app_db_password
# MONGO_DATABASE: parrot
# MONGO_USERNAME: app_db_username
# MONGO_PASSWORD: app_db_password
    secrets:
      - root_db_admin
      - root_db_username
      - root_db_password
      - app_db_username
      - app_db_password
      - app_db_name

secrets:
  root_db_admin:
    file: secrets/root_db_admin.txt
  root_db_username:
    file: secrets/root_db_username.txt
  root_db_password:
    file: secrets/root_db_password.txt
  app_db_username:
    file: secrets/app_db_username
  app_db_password:
    file: secrets/app_db_password
  app_db_name:
    file: secrets/app_db_name